/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CopyUnpkgToClipboard {
    }
}
declare global {
    interface HTMLCopyUnpkgToClipboardElement extends Components.CopyUnpkgToClipboard, HTMLStencilElement {
    }
    var HTMLCopyUnpkgToClipboardElement: {
        prototype: HTMLCopyUnpkgToClipboardElement;
        new (): HTMLCopyUnpkgToClipboardElement;
    };
    interface HTMLElementTagNameMap {
        "copy-unpkg-to-clipboard": HTMLCopyUnpkgToClipboardElement;
    }
}
declare namespace LocalJSX {
    interface CopyUnpkgToClipboard {
    }
    interface IntrinsicElements {
        "copy-unpkg-to-clipboard": CopyUnpkgToClipboard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "copy-unpkg-to-clipboard": LocalJSX.CopyUnpkgToClipboard & JSXBase.HTMLAttributes<HTMLCopyUnpkgToClipboardElement>;
        }
    }
}
